/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка работоспособности */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Идентификация спектра (UC-01) */
        post: operations["identify_api_v1_identify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identify/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пакетная идентификация (UC-06) */
        post: operations["identify_batch_api_v1_identify_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Поиск соединений в локальной базе (UC-04) */
        get: operations["list_compounds_api_v1_compounds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compounds/structure.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SVG структурной формулы по SMILES (без БД, phase 1) */
        get: operations["render_structure_by_smiles_api_v1_compounds_structure_svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compounds/{compound_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка соединения (UC-02) */
        get: operations["get_compound_api_v1_compounds__compound_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compounds/{compound_id}/structure.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SVG структурной формулы (CLAUDE.md §7) */
        get: operations["render_structure_api_v1_compounds__compound_id__structure_svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spectra": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить спектр в локальную базу (UC-03) */
        post: operations["add_spectrum_api_v1_spectra_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История идентификаций (UC-08) */
        get: operations["list_history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить дефолтные настройки (UC-07) */
        get: operations["read_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Сохранить настройки (echo на phase 1) */
        patch: operations["update_settings_api_v1_settings_patch"];
        trace?: never;
    };
    "/api/v1/functional-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Полный список функциональных групп (25 строк, §5.4.1) */
        get: operations["list_functional_groups_api_v1_functional_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description Унифицированный объект ошибки в `detail`.
         */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: string;
            } | null;
        };
        /** BatchIdentificationItemResponse */
        BatchIdentificationItemResponse: {
            /** Filename */
            filename: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            result?: components["schemas"]["IdentificationResponse"] | null;
            error?: components["schemas"]["ApiError"] | null;
        };
        /** BatchIdentificationResponse */
        BatchIdentificationResponse: {
            /** Items */
            items: components["schemas"]["BatchIdentificationItemResponse"][];
            /** Total Processing Time Ms */
            total_processing_time_ms: number;
        };
        /** Body_add_spectrum_api_v1_spectra_post */
        Body_add_spectrum_api_v1_spectra_post: {
            /**
             * File
             * @description JCAMP-DX/CSV-спектр
             */
            file: string;
            /**
             * Smiles
             * @description SMILES-строка соединения
             */
            smiles: string;
            /** Name */
            name?: string | null;
            /**
             * Source
             * @default manual
             */
            source: string;
        };
        /** Body_identify_api_v1_identify_post */
        Body_identify_api_v1_identify_post: {
            /**
             * File
             * @description JCAMP-DX или CSV
             */
            file: string;
            /**
             * Include Gradcam
             * @description Включить Grad-CAM для top-1 группы
             * @default true
             */
            include_gradcam: boolean;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** Body_identify_batch_api_v1_identify_batch_post */
        Body_identify_batch_api_v1_identify_batch_post: {
            /**
             * Files
             * @description До 20 файлов JCAMP-DX/CSV
             */
            files: string[];
            /**
             * Include Gradcam
             * @default false
             */
            include_gradcam: boolean;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /**
         * CompoundCandidate
         * @description Кандидат-соединение из FAISS-ретривала с результатом cross-validation.
         */
        CompoundCandidate: {
            /**
             * Rank
             * @description ранг в выдаче, 1 — самый похожий
             */
            rank: number;
            /** Compound Id */
            compound_id: number;
            /** Smiles */
            smiles: string;
            /** Name */
            name?: string | null;
            /** Formula */
            formula?: string | null;
            /** Cas Number */
            cas_number?: string | null;
            /**
             * Score
             * @description cosine similarity (inner product на L2-нормированных эмбеддингах)
             */
            score: number;
            /**
             * Consistent
             * @description True если cross-validation помечает кандидата как согласованного
             */
            consistent: boolean;
            /** Jaccard */
            jaccard: number;
            /**
             * Matched Groups
             * @default []
             */
            matched_groups: string[];
            /**
             * Missing Groups
             * @default []
             */
            missing_groups: string[];
            /**
             * Extra Groups
             * @default []
             */
            extra_groups: string[];
        };
        /** CompoundDetailResponse */
        CompoundDetailResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Smiles */
            smiles: string;
            /** Formula */
            formula: string | null;
            /** Cas Number */
            cas_number: string | null;
            /** Iupac Name */
            iupac_name: string | null;
            /** Inchi */
            inchi: string | null;
            /** Inchi Key */
            inchi_key: string | null;
            /** Molecular Weight */
            molecular_weight: number | null;
            /** Functional Groups */
            functional_groups: string[];
            /** Spectra Count */
            spectra_count: number;
        };
        /** CompoundSummary */
        CompoundSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Smiles */
            smiles: string;
            /** Formula */
            formula: string | null;
            /** Cas Number */
            cas_number: string | null;
        };
        /**
         * FunctionalGroupPrediction
         * @description Предсказание одной функциональной группы (§4.4.3, §4.4.5).
         */
        FunctionalGroupPrediction: {
            /**
             * Code
             * @description код группы в стиле FG01..FG25
             */
            code: string;
            /**
             * Name
             * @description имя группы (alcohol_OH, ...)
             */
            name: string;
            /** Probability */
            probability: number;
            /** Threshold */
            threshold: number;
            /** Predicted */
            predicted: boolean;
        };
        /**
         * FunctionalGroupResponse
         * @description Справочная запись функциональной группы (Этап 13).
         */
        FunctionalGroupResponse: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Characteristic Bands */
            characteristic_bands?: string | null;
        };
        /**
         * GradCamPayload
         * @description Активационная карта Grad-CAM для одной функциональной группы (§6.10).
         */
        GradCamPayload: {
            /** Group Code */
            group_code: string;
            /** Group Name */
            group_name: string;
            /** Values */
            values: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HistoryEntryResponse */
        HistoryEntryResponse: {
            /** Request Id */
            request_id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Status */
            status: string;
            /** Processing Time Ms */
            processing_time_ms: number | null;
            /** Input Filename */
            input_filename: string | null;
            /** Top Predicted Groups */
            top_predicted_groups: string[];
        };
        /**
         * IdentificationResponse
         * @description Ответ POST /api/v1/identify.
         */
        IdentificationResponse: {
            /** Request Id */
            request_id?: number | null;
            /** Predictions */
            predictions: components["schemas"]["FunctionalGroupPrediction"][];
            /** Candidates */
            candidates: components["schemas"]["CompoundCandidate"][];
            gradcam?: components["schemas"]["GradCamPayload"] | null;
            /** Spectrum */
            spectrum?: number[] | null;
            /** Spectrum Length */
            spectrum_length: number;
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
            /** Threshold Mode */
            threshold_mode: string;
            /** Processing Time Ms */
            processing_time_ms: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** PaginatedCompoundsResponse */
        PaginatedCompoundsResponse: {
            /** Data */
            data: components["schemas"]["CompoundSummary"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /** PaginatedHistoryResponse */
        PaginatedHistoryResponse: {
            /** Data */
            data: components["schemas"]["HistoryEntryResponse"][];
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Total */
            total: number;
        };
        /**
         * SettingsResponse
         * @description Параметры идентификации и предобработки (Этап 13, UC-07).
         *
         *     Phase 1: persistence — только localStorage клиента. PATCH-эндпоинт делает
         *     echo (валидация + 200 с тем же payload), реальная запись в БД — phase 2.
         */
        SettingsResponse: {
            /**
             * Language
             * @default ru
             * @enum {string}
             */
            language: "ru" | "en";
            /**
             * Include Gradcam
             * @default true
             */
            include_gradcam: boolean;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /**
             * Threshold
             * @default 0.5
             */
            threshold: number;
            /**
             * Baseline Method
             * @default asls
             * @enum {string}
             */
            baseline_method: "asls" | "none";
            /**
             * Normalize Method
             * @default snv
             * @enum {string}
             */
            normalize_method: "snv" | "minmax";
            /**
             * Savgol Window
             * @default 11
             */
            savgol_window: number;
            /**
             * Savgol Polyorder
             * @default 2
             */
            savgol_polyorder: number;
        };
        /** SpectrumCreatedResponse */
        SpectrumCreatedResponse: {
            /** Spectrum Id */
            spectrum_id: number;
            /** Compound Id */
            compound_id: number;
            /**
             * Status
             * @constant
             */
            status: "created";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    identify_api_v1_identify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_identify_api_v1_identify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identify_batch_api_v1_identify_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_identify_batch_api_v1_identify_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchIdentificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_compounds_api_v1_compounds_get: {
        parameters: {
            query?: {
                /** @description Поисковая строка */
                q?: string | null;
                /** @description Список кодов функциональных групп (FG01..FG25) */
                functional_groups?: string[] | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCompoundsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_structure_by_smiles_api_v1_compounds_structure_svg_get: {
        parameters: {
            query: {
                /** @description SMILES соединения */
                smiles: string;
                width?: number;
                height?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_compound_api_v1_compounds__compound_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compound_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompoundDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_structure_api_v1_compounds__compound_id__structure_svg_get: {
        parameters: {
            query?: {
                width?: number;
                height?: number;
            };
            header?: never;
            path: {
                compound_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_spectrum_api_v1_spectra_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_spectrum_api_v1_spectra_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpectrumCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_api_v1_history_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                date_from?: string | null;
                date_to?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_functional_groups_api_v1_functional_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionalGroupResponse"][];
                };
            };
        };
    };
}
